const data = {  
   "questions":[  
      {  
         "id":2,
         "enabled":1,
         "category":"Banking & Finance",
         "question":"Which city is the financial centre of Germany?",
         "option_1":"Frankfurt ",
         "option_2":"Berlin",
         "option_3":"Hamburg ",
         "option_4":"Munich",
         "correct_option":"1"
      },
      {  
         "id":3,
         "enabled":1,
         "category":"Banking & Finance",
         "question":"What name is given to a market when share prices are rising?",
         "option_1":"Rocket",
         "option_2":"Bull ",
         "option_3":"Bear",
         "option_4":"Climber",
         "correct_option":"2"
      },
      {  
         "id":4,
         "enabled":1,
         "category":"Banking & Finance",
         "question":"What\u2019s the name of Malaysia\u2019s currency?",
         "option_1":"Baht",
         "option_2":"Dong",
         "option_3":"Kyat",
         "option_4":"Ringgit",
         "correct_option":"4"
      }
    //   {  
    //      "id":5,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"Which country is not a \u2018Pacific Puma?",
    //      "option_1":"Chile",
    //      "option_2":"Columbia",
    //      "option_3":"Bolivia",
    //      "option_4":"Peru",
    //      "correct_option":"3"
    //   },
    //   {  
    //      "id":6,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"Which is the largest economy in Africa by GDP?",
    //      "option_1":"South Africa",
    //      "option_2":"Nigeria",
    //      "option_3":"Egypt",
    //      "option_4":"Morocco",
    //      "correct_option":"1"
    //   },
    //   {  
    //      "id":7,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"Which country does not use the Dinar?",
    //      "option_1":"Kuwait",
    //      "option_2":"Jordan",
    //      "option_3":"Bahrain",
    //      "option_4":"Qatar",
    //      "correct_option":"4"
    //   },
    //   {  
    //      "id":8,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"The production possibility curve is also known as the\u2026?",
    //      "option_1":"Steel & soap curve",
    //      "option_2":"Guns & butter curve",
    //      "option_3":"Cheese & biscuits curve",
    //      "option_4":"Ships & shoes curve",
    //      "correct_option":"2"
    //   },
    //   {  
    //      "id":9,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"Which futures market features in the finale of the film Trading Places?",
    //      "option_1":"Sugar",
    //      "option_2":"Pork Bellies",
    //      "option_3":"Orange Juice ",
    //      "option_4":"Cotton",
    //      "correct_option":"3"
    //   },
    //   {  
    //      "id":10,
    //      "enabled":1,
    //      "category":"Banking & Finance",
    //      "question":"Which of these is not a US Market Index?",
    //      "option_1":"DOW",
    //      "option_2":"NYSX",
    //      "option_3":"NASDAQ",
    //      "option_4":"S&P",
    //      "correct_option":"2"
    //   }
      // temp
        //   {  
        //      "id":11,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"What does IPO stand for?",
        //      "option_1":"International Pricing Option",
        //      "option_2":"Initial Public Offering",
        //      "option_3":"Insider Pricing Offence",
        //      "option_4":"International Procurement Order",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":12,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"A currency established by government regulation is called?",
        //      "option_1":"Alfa",
        //      "option_2":"Ford ",
        //      "option_3":"Fiat ",
        //      "option_4":"Seat",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":14,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"What name is given to non-investment grade bonds?",
        //      "option_1":"Baloney",
        //      "option_2":"Rubbish",
        //      "option_3":"Junk",
        //      "option_4":"Trash",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":15,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"What do the letters AIM stand for?",
        //      "option_1":"Average Investment Margin",
        //      "option_2":"Alternative Investment Market",
        //      "option_3":"Appreciated Investment Margin",
        //      "option_4":"African Investment Market",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":16,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Where is the European Central Bank?",
        //      "option_1":"Brussels",
        //      "option_2":"Amsterdam",
        //      "option_3":"Strasbourg",
        //      "option_4":"Frankfurt",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":17,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Which bestselling book was written by Thomas Piketty?",
        //      "option_1":"The Undercover Economist",
        //      "option_2":"Super Freakonomics",
        //      "option_3":"Capital in the Twenty-First Century",
        //      "option_4":"Economics for Dummies",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":18,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"An event that can be anticipated to a degree is called a\u2026?",
        //      "option_1":"Grey Swan",
        //      "option_2":"Black Swan ",
        //      "option_3":"White Swan ",
        //      "option_4":"Purple Swan",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":19,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Which term is used for an unpredictable event?",
        //      "option_1":"Black Raven",
        //      "option_2":"Black Swan ",
        //      "option_3":"Black Crow",
        //      "option_4":"Black Badger",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":21,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"The Nikkei is the Stock Exchange Index of\u2026?",
        //      "option_1":"Shanghai",
        //      "option_2":"Singapore",
        //      "option_3":"Tokyo",
        //      "option_4":"Hong Kong",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":22,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Citi facilitates the flow of how many dollars daily?",
        //      "option_1":"4 million",
        //      "option_2":"4 billion",
        //      "option_3":"4 trillion",
        //      "option_4":"4 quadrillion",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":23,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Citi has a presence in how many countries?",
        //      "option_1":"38",
        //      "option_2":"58",
        //      "option_3":"78",
        //      "option_4":"98",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":24,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Citi has local trading desks in how many markets?",
        //      "option_1":"7",
        //      "option_2":"17",
        //      "option_3":"77",
        //      "option_4":"177",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":25,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Citi serves how many Fortune 500 companies?",
        //      "option_1":"8%",
        //      "option_2":"18%",
        //      "option_3":"50%",
        //      "option_4":"80%",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":26,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Citi has a presence in how many EMEA countries?",
        //      "option_1":"4",
        //      "option_2":"14",
        //      "option_3":"54",
        //      "option_4":"104",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":27,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"What % of the Citi workforce is female?",
        //      "option_1":"31%",
        //      "option_2":"41%",
        //      "option_3":"51%",
        //      "option_4":"61%",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":28,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"Which is NOT one of the 3 E\u2019s of Citi\u2019s Learning Philosophy?",
        //      "option_1":"Exuberance ",
        //      "option_2":"Experience ",
        //      "option_3":"Exposure ",
        //      "option_4":"Education",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":29,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"How many people does Citi employ globally?",
        //      "option_1":"2,140",
        //      "option_2":"21,400",
        //      "option_3":"214,000",
        //      "option_4":"2,140,000",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":30,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"How many volunteers took part in Citi\u2019s 12th Annual Global Community Day? ",
        //      "option_1":"1,000",
        //      "option_2":"10,000",
        //      "option_3":"100,000",
        //      "option_4":"1,000 000",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":31,
        //      "enabled":1,
        //      "category":"Banking & Finance",
        //      "question":"How much has the Citi foundation pledged to empower global urban youth?",
        //      "option_1":"1 million dollars",
        //      "option_2":"10 million dollars",
        //      "option_3":"50 million dollars",
        //      "option_4":"100 million dollars",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":32,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Rich individuals who invest in startups are often called\u2026?",
        //      "option_1":"Angels",
        //      "option_2":"Tigers",
        //      "option_3":"Dragons",
        //      "option_4":"Vultures",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":33,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Investment in a startup is often referred to as\u2026?",
        //      "option_1":"Pipeline funding",
        //      "option_2":"Seed funding ",
        //      "option_3":"Acorn funding",
        //      "option_4":"Eye-twinkle funding",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":34,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Which of these is not a major crowdfunding platform?",
        //      "option_1":"Fundable",
        //      "option_2":"Kickstarter",
        //      "option_3":"Rockethub",
        //      "option_4":"Beanfeast",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":35,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Entrepreneur Steve Wozniak is associated with\u2026?",
        //      "option_1":"Microsoft",
        //      "option_2":"Apple",
        //      "option_3":"Facebook",
        //      "option_4":"Google",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":38,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"\u2018Back to the Future\u2019 features which automobile entrepreneur\u2019s car?",
        //      "option_1":"Maserati",
        //      "option_2":"DeLorean",
        //      "option_3":"Bugatti",
        //      "option_4":"Morris",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":39,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Elon Musk is the founder of which car company?",
        //      "option_1":"Venturi",
        //      "option_2":"Tango",
        //      "option_3":"Tesla",
        //      "option_4":"Wheeg",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":41,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Which dot com business did Martha Lane Fox launch?",
        //      "option_1":"Lastminute.com",
        //      "option_2":"ASOS",
        //      "option_3":"Experian",
        //      "option_4":"Skyscanner",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":43,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"What do the initials in ASOS stand for?",
        //      "option_1":"A Smarter Online Shop",
        //      "option_2":"As Seen On Screen ",
        //      "option_3":"Amy Sharpe\u2019s Online Shop ",
        //      "option_4":"All Styles Only Shopping",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":44,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Which term means financing without funding?",
        //      "option_1":"Bootstrapping ",
        //      "option_2":"Lace-tying",
        //      "option_3":"Self-starting",
        //      "option_4":"Pre-loading",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":47,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Which of these was a UK startup?",
        //      "option_1":"Deliveroo",
        //      "option_2":"Snapchat",
        //      "option_3":"Twitter",
        //      "option_4":"Uber",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":48,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"What was Snapchat originally called?",
        //      "option_1":"Chatsnap",
        //      "option_2":"Coo-ee!",
        //      "option_3":"Picaboo",
        //      "option_4":"Fastchat",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":50,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"Which product is associated with James Dyson?",
        //      "option_1":"Airblade",
        //      "option_2":"Jet Towel",
        //      "option_3":"Vornado",
        //      "option_4":"Hand Hoover",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":51,
        //      "enabled":1,
        //      "category":"Entrepreneurship",
        //      "question":"What is the name of the entrepreneur behind Easyjet?",
        //      "option_1":"Phillip Green",
        //      "option_2":"Michael O\u2019Leary ",
        //      "option_3":"Stelios Haji-Ioannou",
        //      "option_4":"Richard Branson",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":52,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired the invention of the GoPro camera?",
        //      "option_1":"Road rage towards cyclists",
        //      "option_2":"Wanting to take selfies while surfing",
        //      "option_3":"Trying to film a downhill ski run",
        //      "option_4":"Putting a camera on a pet dog",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":53,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired Ikea\u2019s creation?",
        //      "option_1":"A doll\u2019s house furniture set",
        //      "option_2":"Taking the legs off a table to fit it in a car",
        //      "option_3":"A love of complex instructions",
        //      "option_4":"A plate of Swedish meatballs",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":54,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired the creation of the Red Bull drink?",
        //      "option_1":"A Jagermeister-induced hangover",
        //      "option_2":"Trying out a drink to cure jetlag",
        //      "option_3":"Drinking Lucozade at a bullfight",
        //      "option_4":"An all-night revision session",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":55,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Which Beatles song came to Paul McCartney in a dream?",
        //      "option_1":"Penny Lane",
        //      "option_2":"Yesterday",
        //      "option_3":"Eleanor Rigby",
        //      "option_4":"I\u2019m only sleeping",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":56,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired the creation of Whatsapp?",
        //      "option_1":"The cost of SMS picture messages",
        //      "option_2":"The cost of calling Ukraine from the USA",
        //      "option_3":"A TV ad for a US beer brand",
        //      "option_4":"A university competition",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":57,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired the invention of instant noodles?",
        //      "option_1":"Watching people queue for soup on a cold day",
        //      "option_2":"A journey on the trans-Siberian express",
        //      "option_3":"Cooking regular noodles in a kettle",
        //      "option_4":"A competition run by the Japanese government",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":58,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"What inspired the creation of Airbnb?",
        //      "option_1":"Sleeping in an airline pilot\u2019s spare room",
        //      "option_2":"Renting out an airbed for cash",
        //      "option_3":"Being stranded for the night in New York",
        //      "option_4":"Watching a repeat of a Friends episode",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":59,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Who had the world\u2019s \u2018first\u2019 Eureka moment?",
        //      "option_1":"Diogenes",
        //      "option_2":"Archimedes",
        //      "option_3":"Socrates",
        //      "option_4":"Aristotle ",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":60,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Who created the idea of the invisible hand?",
        //      "option_1":"Isaac Newton",
        //      "option_2":"Adam Smith",
        //      "option_3":"Benjamin Franklin",
        //      "option_4":"Karl Marx",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":61,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Who is credited with inventing the first vaccine?",
        //      "option_1":"Louis Pasteur",
        //      "option_2":"Alexander Fleming",
        //      "option_3":"Robert Koch",
        //      "option_4":"Edward Jenner",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":62,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"In which year did was the World Wide Web invented?",
        //      "option_1":"1971",
        //      "option_2":"1981",
        //      "option_3":"1989",
        //      "option_4":"1991",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":63,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Which brothers invented the ballpoint pen?",
        //      "option_1":"The Parkers",
        //      "option_2":"The Bics",
        //      "option_3":"The Biros ",
        //      "option_4":"The Stabilos",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":64,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"In which year were Post-it Notes invented?",
        //      "option_1":"1954",
        //      "option_2":"1964",
        //      "option_3":"1974",
        //      "option_4":"1984",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":65,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Inventor Daisuke Inoue failed to patent which idea?",
        //      "option_1":"Karaoke Machine",
        //      "option_2":"Polaroid Camera",
        //      "option_3":"Tamagotchi",
        //      "option_4":"Microwave Oven",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":66,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"When was the bread slicer invented?",
        //      "option_1":"1888",
        //      "option_2":"1908",
        //      "option_3":"1928",
        //      "option_4":"1948",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":67,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"Which invention came first?",
        //      "option_1":"Paper Towel",
        //      "option_2":"Ice cream cone",
        //      "option_3":"Yo-yo",
        //      "option_4":"Trampoline",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":70,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"When was the first true mobile phone call made?",
        //      "option_1":"1963",
        //      "option_2":"1973",
        //      "option_3":"1983",
        //      "option_4":"1993",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":71,
        //      "enabled":1,
        //      "category":"Ideas, big & small",
        //      "question":"As of 2017, how old is the Cash Machine?",
        //      "option_1":"100 years",
        //      "option_2":"50 years",
        //      "option_3":"40 years",
        //      "option_4":"30 years",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":72,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which is the odd one out?",
        //      "option_1":"Calf",
        //      "option_2":"Kid",
        //      "option_3":"Fawn",
        //      "option_4":"Nanny",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":73,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which name has something in common with Bob?",
        //      "option_1":"Hannah",
        //      "option_2":"John",
        //      "option_3":"Sarah",
        //      "option_4":"Miley",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":74,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which is NOT a prime number?",
        //      "option_1":"17",
        //      "option_2":"29",
        //      "option_3":"85",
        //      "option_4":"97",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":75,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"24 kilometres is roughly equal to\u2026?",
        //      "option_1":"13 miles",
        //      "option_2":"15 miles",
        //      "option_3":"18 miles",
        //      "option_4":"20 miles",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":76,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"If London = 6, Hong Kong = 8 and Shanghai = 8, Frankfurt = ?",
        //      "option_1":"6",
        //      "option_2":"7",
        //      "option_3":"8",
        //      "option_4":"9",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":77,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"If A=1, B=2, C=3 etc, which name has the highest added total?",
        //      "option_1":"Kenny",
        //      "option_2":"Jenny",
        //      "option_3":"Penny",
        //      "option_4":"Lenny",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":78,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which is an anagram of South Africa\u2019s currency?",
        //      "option_1":"Knit",
        //      "option_2":"Darn",
        //      "option_3":"Stitch",
        //      "option_4":"Crochet",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":79,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"If Denmark is red and white \u00a0and Sweden is yellow and blue, what is Scotland?",
        //      "option_1":"Yellow and red",
        //      "option_2":"Green and blue\u00a0",
        //      "option_3":"Red and green",
        //      "option_4":"Blue and white",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":80,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Bob wakes up to a digital alarm clock showing his name. What time is it?",
        //      "option_1":"6 o\u2019clock",
        //      "option_2":"6 minutes past 8",
        //      "option_3":"Half past 7",
        //      "option_4":"8 minutes past 8",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":81,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"If the five visible sides of a dice total 19, which number is not visible?",
        //      "option_1":"1",
        //      "option_2":"2",
        //      "option_3":"4",
        //      "option_4":"6",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":82,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"EGGS = 5. BACON = 2. SAUSAGES = 19. What does MUESLI equal?",
        //      "option_1":"7",
        //      "option_2":"11",
        //      "option_3":"13",
        //      "option_4":"15",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":83,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Starting at midnight, your clock loses 10 minutes an hour. What is the real time when it shows 5.50am? ",
        //      "option_1":"6.50am",
        //      "option_2":"7.00am",
        //      "option_3":"7.10am",
        //      "option_4":"7.20am",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":84,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Chas sees three cars lined up with international registration plates spelling out his name. Which country is NOT represented?",
        //      "option_1":"Austria",
        //      "option_2":"Croatia",
        //      "option_3":"Switzerland",
        //      "option_4":"Sweden",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":85,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which number comes next in this series 7, 10, 8, 11, 9, 12, ...?",
        //      "option_1":"7",
        //      "option_2":"10",
        //      "option_3":"12",
        //      "option_4":"13",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":86,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which of these words is the odd one out?",
        //      "option_1":"MIAMI",
        //      "option_2":"MINIM ",
        //      "option_3":"JAMMY",
        //      "option_4":"AMMAN",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":87,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which number is next in this sequence? 20, 1, 18, 7, 4, 13\u2026?",
        //      "option_1":"6",
        //      "option_2":"3",
        //      "option_3":"11",
        //      "option_4":"19",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":88,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Which is the odd one out?",
        //      "option_1":"Crimson",
        //      "option_2":"Violet",
        //      "option_3":"Ruby",
        //      "option_4":"Scarlet",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":89,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"How many of each kind of animal did Moses take on the ark?",
        //      "option_1":"0",
        //      "option_2":"2",
        //      "option_3":"3",
        //      "option_4":"4",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":90,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"Horse is to Mare as\u2026? ",
        //      "option_1":"Fox is to Vixen",
        //      "option_2":"Duck is to Goose",
        //      "option_3":"Dog is to Puppy",
        //      "option_4":"Donkey is to Pony",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":91,
        //      "enabled":1,
        //      "category":"Analytical thinking",
        //      "question":"An Eskimo is looking out of his window at his home in Alaska. He saw a huge bear walking towards his house. What colour is the bear?",
        //      "option_1":"Brown",
        //      "option_2":"Black",
        //      "option_3":"Red",
        //      "option_4":"White",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":92,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is a sign of emotional intelligence?",
        //      "option_1":"Over-reacting to situations",
        //      "option_2":"Dwelling on past mistakes",
        //      "option_3":"Being open to change",
        //      "option_4":"Difficulty reading other\u2019s emotions",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":93,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is NOT a sign of emotional intelligence?",
        //      "option_1":"Self-awareness",
        //      "option_2":"Perfectionism",
        //      "option_3":"Ability to control emotions",
        //      "option_4":"Curiosity about people",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":94,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is a sign of emotional intelligence?",
        //      "option_1":"Selfishness",
        //      "option_2":"Knowing when to say \u201cno\u201d",
        //      "option_3":"Making time for play",
        //      "option_4":"Willingness to help others",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":95,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is a sign of emotional intelligence?",
        //      "option_1":"Impatience",
        //      "option_2":"Self-awareness",
        //      "option_3":"Abruptness",
        //      "option_4":"Defensiveness",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":96,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is NOT a sign of emotional intelligence?",
        //      "option_1":"Moving on from mistakes",
        //      "option_2":"Making time to destress",
        //      "option_3":"Associating with positive people",
        //      "option_4":"Fearing loss of control",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":97,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Emotionally intelligent people are often described as\u2026?",
        //      "option_1":"Poor listeners",
        //      "option_2":"Jealous of others",
        //      "option_3":"Lacking empathy",
        //      "option_4":"Aware of their own weaknesses",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":98,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Emotionally intelligent people tend to\u2026?",
        //      "option_1":"Defuse conflicts effectively",
        //      "option_2":"Blame others for mistakes",
        //      "option_3":"Make snap decisions",
        //      "option_4":"Put opinion ahead of evidence",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":99,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Emotionally intelligent people tend to\u2026?",
        //      "option_1":"Make inappropriate jokes",
        //      "option_2":"Take criticism badly",
        //      "option_3":"Ignore evidence",
        //      "option_4":"Avoid stereotyping",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":100,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with low emotional intelligence tend to\u2026?",
        //      "option_1":"Look to the future, not the past ",
        //      "option_2":"Be poor listeners",
        //      "option_3":"Control their emotions easily ",
        //      "option_4":"Recognize the viewpoint of others",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":101,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with high emotional intelligence\u2026?",
        //      "option_1":"Can\u2019t read other\u2019s emotions",
        //      "option_2":"Look for solutions, not problems",
        //      "option_3":"Are easily offended",
        //      "option_4":"Are poor listeners",
        //      "correct_option":"2"
        //   },
        //   {  
        //      "id":102,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which is a trait of emotional intelligence?",
        //      "option_1":"Understanding other\u2019s feelings",
        //      "option_2":"Being resistant to change",
        //      "option_3":"Escalating conflict",
        //      "option_4":"Making inappropriate comments",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":103,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with low emotional intelligence\u2026?",
        //      "option_1":"Enjoy group situations",
        //      "option_2":"Move on from mistakes",
        //      "option_3":"Are good listeners",
        //      "option_4":"Make snap judgements",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":104,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with high emotional intelligence\u2026?",
        //      "option_1":"Lose their temper in front of others",
        //      "option_2":"Ignore the concerns of others",
        //      "option_3":"Are blind to their weaknesses",
        //      "option_4":"Manage disputes well",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":105,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which is a trait of emotional intelligence?",
        //      "option_1":"Thinking before responding",
        //      "option_2":"Letting stress build up",
        //      "option_3":"Repeating the same mistakes",
        //      "option_4":"Over-reacting to criticism",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":106,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"Which trait is NOT a sign of emotional intelligence?",
        //      "option_1":"Fearing loss of control",
        //      "option_2":"Making time for play",
        //      "option_3":"Acting in a consistent way",
        //      "option_4":"Having empathy for others",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":107,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with high emotional intelligence are\u2026?",
        //      "option_1":"Quick to get angry",
        //      "option_2":"Insensitive to other\u2019s problems",
        //      "option_3":"Easily offended",
        //      "option_4":"Open to new ideas",
        //      "correct_option":"4"
        //   },
        //   {  
        //      "id":108,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with low emotional intelligence\u2026?",
        //      "option_1":"Struggle to read body language",
        //      "option_2":"Are aware of their own faults",
        //      "option_3":"Think before they speak",
        //      "option_4":"See other\u2019s point of view",
        //      "correct_option":"1"
        //   },
        //   {  
        //      "id":109,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with high emotional intelligence\u2026?",
        //      "option_1":"Talk over other people\u2019s conversations",
        //      "option_2":"Make inappropriate jokes",
        //      "option_3":"Give credit to others",
        //      "option_4":"Struggle to control their emotions",
        //      "correct_option":"3"
        //   },
        //   {  
        //      "id":110,
        //      "enabled":1,
        //      "category":"Emotional Intelligence",
        //      "question":"People with high emotional intelligence\u2026?",
        //      "option_1":"Focus on what\u2019s gone wrong",
        //      "option_2":"Look to blame others",
        //      "option_3":"Take ownership of problems ",
        //      "option_4":"Hold grudges against colleagues",
        //      "correct_option":"3"
        //   }
   ],
   "categories":[  
      "Banking & Finance",
      "Entrepreneurship",
      "Ideas, big & small",
      "Analytical thinking",
      "Emotional Intelligence"
   ],
   "count":98
}

export default data